In [48]:
#create matrix
import numpy as np
matrix=np.array([[2,4,6],[6,6,5],[3,5,3]])
print(matrix)

[[2 4 6]
 [6 6 5]
 [3 5 3]]


In [56]:
#mean
mean=np.mean(matrix)
print(mean)

#median
median=np.median(matrix)
print(median)

#mode
from scipy import stats
mode=stats.mode(matrix,axis=1)  #axis=0 for column,axis=1 for row
print(mode)

#determinant
determinant=np.linalg.det(matrix)
print(determinant)

#inverse
inverse=np.linalg.inv(matrix)
print(inverse)

4.444444444444445
5.0
ModeResult(mode=array([2, 6, 3], dtype=int64), count=array([1, 2, 2], dtype=int64))
46.0
[[-0.15217391  0.39130435 -0.34782609]
 [-0.06521739 -0.26086957  0.56521739]
 [ 0.26086957  0.04347826 -0.26086957]]


In [ ]:
#inverse formula - https://byjus.com/maths/inverse-matrix/